### ISSUE TITLE
How about add a function that can check memory around an address?

### ISSUE THREAD

**Issue by rickcheung** [valarnin/NTRRemoteDebugger#21] opened 2017-03-08 08:08 UTC
I want to have function that let us view the memory (say 1024 bytes) around a specific address, so that i can use the data to check whether i edit the correct address or make further change in the memory. This function is extremely useful in game cheating, such as finding where the item data is stored in the memory.

I really want to see this function :)

P.S: I see a milestone is added for this function but seems that is not implemented for a long time.

**Comment by phecdaDia** [comment] 2017-03-09 18:57
I don't think this project is still actively supported.  
The last commit was 10 months ago and there are still open issues from one year ago.  

You could try to use the normal NTR debugger or similar ( I haven't looked at the recent developments ) to dump the memory around an address.

**Comment by valarnin** [comment] 2017-03-10 01:53
I do plan to return to this project, but free time remains an issue for me.

The main barrier to implementing most of the remaining features, like the memory viewer, is a workable GUI.

I'm not aware of any good way to handle displaying a memory dump using native components without coding some extensive additional GUI pieces. Writing such a component would be a significant timesink.

**Comment by f-israel** [comment] 2017-06-24 07:36
Am I wrong or is Issue #7 addressing this? If so I would suggest to close this one.

**Comment by valarnin** [comment] 2017-06-25 01:20
This seems to be #7 plus being able to modify the displayed memory. I'm going to close this issue as a duplicate of #7 and note that additional functionality there.

Not sure why I didn't get an email notification for this issue when it was originally created, strange.

**Closed as completed by valarnin** 2017-06-25 01:20 UTC
